name: AWS CF Destroy

on:
  workflow_dispatch:
    inputs:
      cf_stack_name:
        description: 'Name of the stack to destroy'
        required: true

jobs:
  cf_destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: aws cloudformation delete-stack --stack-name ${{ inputs.cf_stack_name }}
      - run: aws cloudformation wait stack-delete-complete --stack-name --stack-name ${{ inputs.cf_stack_name }}